# Build the application

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Cache Node
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{matrix.os}}-${{ hashFiles('./package-lock.json') }}

      # Cache Next.js
      - uses: actions/cache@v3
        with:
          path: ./.next
          key: next-cache

      - name: Install Node.js v16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
     
      - name: Install node dependencies
        run: npm install

      - name: Build application
        run: npm run build

 
