# Deploy to docs.next-hat.com

name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Cache Node
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{matrix.os}}-${{ hashFiles('./package-lock.json') }}

      # Cache Next.js
      - uses: actions/cache@v3
        with:
          path: ./.next
          key: next-cache

      - name: Install Node.js v16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
     
      - name: Install node dependencies
        run: npm install

      - name: Build application
        run: npm run build
  deploy:
    needs: [build]
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success'
    steps:
      - name: Install nanocl CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.next-hat.com/repo/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/next-hat.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/next-hat.gpg] https://download.next-hat.com/repo/linux/ubuntu stable main" | sudo tee /etc/apt/sources.list.d/next-hat.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y nanocl
